server:
  port: 8082

# 配置文件的分离  不同的项目环境读取不同的配置文件
github:
  client:
    id: c196d0ba84d8d5a26586
    secret: 6fe967e53965808a2d559ac770489bd07e0ed115
    uri: http://localhost:8081/callback

# 数据库连接池
spring:
  datasource:
    url: jdbc:mysql://121.37.185.192:3306/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis配置
mybatis:
  # 指定全局配置文件的位置
#  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    # 开启驼峰映射

# 日志信息
logging:
  level:
    com.ling.other.mapper: debug
#debug: true